define(['jquery', "core/ajax"], function($) {
    return {
        init: function() {
            const formElements = $('#create_template_form input, #create_template_form select, #create_template_form textarea');
            const form = $('#create_template_form');
            const saveButton = form.find('#id_save_template_button'); // Update this to the correct ID
            const cancelButton = form.find('#id_cancel_template_button'); // Cancel button

            // Get the current URL, including query parameters
            const currentUrlWithParams = window.location.href;

            // Iterate over each form element to add an event listener for changes.
            formElements.each(function() {
                const element = $(this);
                element.on('change', function() {
                    markTouched(element);
                });

                if (element.is(':checkbox') || element.is(':radio')) {
                    element.on('click', function() {
                        markTouched(element);
                    });
                }
            });

            // Handle save button click (prevent the default form submission).
            saveButton.on('click', function(event) {
                event.preventDefault(); // Prevent the default form submission

                // Gather only touched elements
                let formData = {};
                formElements.each(function() {
                    const element = $(this);
                    if (element.attr('data-touched') === 'true') {
                        const htmlId = element.attr('id');
                        const settingName = htmlId.replace('id_', ''); // Derive the setting name by removing 'id_'
                        formData[settingName] = element.val();
                    }
                });

                // Also add template_name and any other essential values
                formData['template_name'] = form.find('input[name="template_name"]').val();

                // Submit the form data using AJAX
                $.ajax({
                    url: currentUrlWithParams,
                    method: 'POST',
                    data: formData,
                    success: function(response) {
                        try {
                            const responseData = JSON.parse(response);
                            if (responseData.redirect) {
                                // Redirect to the specified URL, generated by Moodle
                                window.location.href = responseData.redirect;
                            } else if (responseData.error) {
                                console.error(responseData.error);
                            }
                        } catch (e) {
                            console.error('Error parsing JSON response:', e);
                            console.error('Response received:', response);
                        }
                    },
                    error: function(xhr, status, error) {
                        console.log('An error occurred while saving the template.');
                        console.log('Status:', status);
                        console.log('Error:', error);
                        console.log('Response:', xhr.responseText);
                    }
                });
            });

            // Handle cancel button click.
            cancelButton.on('click', function(event) {
                event.preventDefault(); // Prevent the default action
                window.location.href = M.cfg.wwwroot + '/local/setcheck/manage_templates.php';
            });

            /**
             * @param {jQuery} element The element to mark as touched.
             */
            function markTouched(element) {
                element.attr('data-touched', 'true');
            }
        }
    };
});
